// Define the cache name and resources to cache
const cacheName = 'Soler-Palau-App-Data-updatedVersionOne';
const cacheResources = [
  '/sp-app/',
  '/sp-app/index.html',
  '/sp-app/assets/icons/favicon.ico',
  '/sp-app/assets/icons/icon.png',
  '/sp-app/assets/icons/favicon.png',
  '/sp-app/assets/icons/icon-v2.png',
  '/sp-app/assets/icons/icon-v3.png',
  '/sp-app/assets/icons/icon-v4.png',
  '/sp-app/assets/icons/icon-v6.png',
  '/sp-app/assets/images/AR.png',
  '/sp-app/assets/images/blog.svg',
  '/sp-app/assets/images/circle-play-solid.svg',
  '/sp-app/assets/images/events.svg',
  '/sp-app/assets/images/fan-solid.svg',
  '/sp-app/assets/images/fan-white.svg',
  '/sp-app/assets/images/file-pdf-solid.svg',
  '/sp-app/assets/images/GD.png',
  '/sp-app/assets/images/helpcenter.svg',
  '/sp-app/assets/images/home.svg',
  '/sp-app/assets/images/library.svg',
  '/sp-app/assets/images/links-nav.svg',
  '/sp-app/assets/images/links.svg',
  '/sp-app/assets/images/Losone-Select-Ceiling.webp',
  '/sp-app/assets/images/new-branch.svg',
  '/sp-app/assets/images/new-rep.svg',
  '/sp-app/assets/images/optisizer.svg',
  '/sp-app/assets/images/PC.png',
  '/sp-app/assets/images/PCD.png',
  '/sp-app/assets/images/PCLP.png',
  '/sp-app/assets/images/PCV.png',
  '/sp-app/assets/images/print-shop.svg',
  '/sp-app/assets/images/product-returns.svg',
  '/sp-app/assets/images/return-back-button.svg',
  '/sp-app/assets/images/right-left-solid.svg',
  '/sp-app/assets/images/right-left-white.svg',
  '/sp-app/assets/images/search-icon.svg',
  '/sp-app/assets/images/Share-outline-01.svg',
  '/sp-app/assets/images/solidplay-white.svg',
  '/sp-app/assets/images/logo-mb.png',
  '/sp-app/assets/images/ACF-recat.png',
  '/sp-app/assets/images/BGH-recat.png',
  '/sp-app/assets/images/CFD-recat.png',
  '/sp-app/assets/images/CM-recat.png',
  '/sp-app/assets/images/CSF-recat.png',
  '/sp-app/assets/images/CTB-recat.png',
  '/sp-app/assets/images/CWD-recat.png',
  '/sp-app/assets/images/DD-recat.png',
  '/sp-app/assets/images/DEDPV-recat.png',
  '/sp-app/assets/images/DF-recat.png',
  '/sp-app/assets/images/HRE-recat.png',
  '/sp-app/assets/images/HRS-recat.png',
  '/sp-app/assets/images/ifab-recat.png',
  '/sp-app/assets/images/ifft-recat.png',
  '/sp-app/assets/images/KSFV-recat.png',
  '/sp-app/assets/images/L2-recat.png',
  '/sp-app/assets/images/L3-recat.png',
  '/sp-app/assets/images/LCE.png',
  '/sp-app/assets/images/Losone-Select-Inline.webp',
  '/sp-app/assets/images/LPD-recat.png',
  '/sp-app/assets/images/LSF-recat.png',
  '/sp-app/assets/images/MD-recat.png',
  '/sp-app/assets/images/PRF-recat.png',
  '/sp-app/assets/images/PV-recat.png',
  '/sp-app/assets/images/RCXII-recat.png',
  '/sp-app/assets/images/RF8-120EC-Low-Profile.webp',
  '/sp-app/assets/images/RF10-160EC-Full-Size.webp',
  '/sp-app/assets/images/RFV-recat.png',
  '/sp-app/assets/images/RLX-recat.png',
  '/sp-app/assets/images/SDB-recat.png',
  '/sp-app/assets/images/SDBD-recat.png',
  '/sp-app/assets/images/SMXD-recat.png',
  '/sp-app/assets/images/smxdk.webp',
  '/sp-app/assets/images/SQB-recat.png',
  '/sp-app/assets/images/SQD-recat.png',
  '/sp-app/assets/images/STXB-recat.png',
  '/sp-app/assets/images/SWF-recat.png',
  '/sp-app/assets/images/TD-MIXVENT-recat.png',
  '/sp-app/assets/images/TD-SILENT-recat.png',
  '/sp-app/assets/images/TDB-recat.png',
  '/sp-app/assets/images/TDD-recat.png',
  '/sp-app/assets/images/tjfu-recat.png',
  '/sp-app/assets/images/TR-recat.png',
  '/sp-app/assets/images/TRC-recat.png',
  '/sp-app/assets/images/trcen-cat.png',
  '/sp-app/assets/images/TRLPe110_RGB.webp',
  '/sp-app/assets/images/TUB-HT-recat.png',
  '/sp-app/assets/images/UBRD-recat.png',
  '/sp-app/assets/images/UBSRD-recat.png',
  '/sp-app/assets/images/vgd-recat.png',
  '/sp-app/assets/css/styles.css',
  '/sp-app/assets/css/cross-ref-style.css',
  '/sp-app/js/main.js',
  '/sp-app/pages/cross-ref.html',
  '/sp-app/pages/library.html',
  '/sp-app/pages/products.html',
  '/sp-app/pages/important-links.html',
  '/sp-app/data/competitors.json',
  '/sp-app/data/cross-references.json',
  '/sp-app/data/documents.json',
  '/sp-app/data/products.json',
  '/sp-app/data/importantLinks.json',
  '/sp-app/components/cross-reference-table.js',
  '/sp-app/components/document-viewer.js',
  '/sp-app/components/navbar.js',
  '/sp-app/components/backButton.js',
  '/sp-app/components/links.js',
  '/sp-app/components/product-list.js',
  '/sp-app/assets/images/DBF-100XC.jpg',
  '/sp-app/assets/images/Tempest-THVLS.png',
  '/sp-app/assets/images/Tornado-THVLS.png',
  '/sp-app/assets/images/UB-recat.png',
  '/sp-app/assets/images/UBS-recat.png',
  'https://www.solerpalau-usa.com/documents/Brochure/assisted-living-application-guide.pdf',
  'https://www.solerpalau-usa.com/documents/Brochure/Ecowatt-Brochure.pdf',
  'https://www.solerpalau-usa.com/documents/Brochure/Food_Retail_Application_Guide.pdf',
  'https://www.solerpalau-usa.com/documents/Brochure/THVLS-Brochure.pdf',
  'https://www.solerpalau-usa.com/documents/Brochure/hotel-resort-application-guide.pdf',
  'https://www.solerpalau-usa.com/documents/Brochure/inline-fan-options.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Jet-Fans-Brochure.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Mixed-Use_Building_Application_Guide.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Mixed-Use_Building_Application_Guide.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/OAS-Brochure.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Premium-CHOICE-Series.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Product-Line-Overview.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Quickship_Catalog.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/radon-mitigation.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/ReFresh-Brochure.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Residential_Application_Guide.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Restaurants_Application_Guide.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/TRV-updated.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Warehouse_Distribution_Center_Application_Guide.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/6002-Flyer-031621.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/Flyer_ACF48.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/BMD.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/Commercial_Products_Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/ECM-MSPD.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/Ecowatt_Drive.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/reFresh-ESME2019.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/ERV_Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/HREB_P.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/Jet-Fans-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/IFFTe50-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/KSFV-FB-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/MDX-ES24VK.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/tie-down-kit-flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/OAS-ProductApp.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/OAS-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PC_Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PC50XP.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PCD110XP.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PCD80XHP.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PCLPXP-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PCLPXP-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PCLPD100XHP-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PCXP.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/PVDEDPV_Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/reFresh-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/RFV8.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/S-Series.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/SMXD.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/SMXDHT-flyer-USA.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/SMXDK-SMXDKHT.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/SMXDK-SMXDKHT.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/STXB-HT.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/STXB-HT.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/TD_Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/TRe-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/tre90-flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/trlpe110-usa-flyer.pdf',
'https://www.solerpalau-usa.com/documents/Flyer/UBSRD-P-Flyer.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ar.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-bgh.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-centrifugal-roof-and-sidewall.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-cfd.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-cm.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-csf.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ctb.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-centrifugal-roof-and-sidewall.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-gd-df-dd.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-hre.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-hrs.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ksfv.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ksfv-fb.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-lc-l2-l3.pdf',
'https://www.solerpalau-usa.com/documents/Brochure/Losone-Select-Series-Brochure.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-centrifugal-roof-and-sidewall.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-lsf.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-pv.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-rcxii.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-rlx.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-sdb.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-sdbd-sdbde.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-smxd-smxdht.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-smxdk-smxdkht-smxdke.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-sqb.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-sqd.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-centrifugal-roof-and-sidewall.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-centrifugal-roof-and-sidewall.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-stxd-stxde.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-swf.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-tdb.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-tdd.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-td-mixvent.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-td-silent.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-tub.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-tub-ht.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ubb-ubx.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ubrd.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ubs.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ubsrd.pdf',
'https://www.solerpalau-usa.com/documents/Catalog/cat-ubsrd-ht.pdf',
'https://www.solerpalau-usa.com/documents/Resource/chemical-resistance-chart.pdf',
'https://www.solerpalau-usa.com/documents/Resource/mounting-arrangement(gd-df-dd).pdf',
'https://www.solerpalau-usa.com/documents/Resource/mounting-arrangement(lc-l2-l3).pdf',
'https://www.solerpalau-usa.com/documents/Resource/sizing-chart(gravity-vent).pdf',
'https://www.solerpalau-usa.com/documents/Resource/static-pressure-calculator.xls',
'https://www.solerpalau-usa.com/documents/Resource/wiring-diagram(esqd).pdf',
'https://www.solerpalau-usa.com/documents/Resource/wiring-diagram(pc).pdf',
'https://www.solerpalau-usa.com/documents/Resource/wiring-diagram(pcd).pdf',
'https://www.solerpalau-usa.com/documents/Resource/wiring-diagram(pcxp).pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-6002-6002A-6002-14A-6002-14B.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-80l.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-acf2.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ar.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-bgh.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-cfd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-cm.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-csf-lsf.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ctb.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-cwd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-dh6-120v.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ecm-dpc.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ecm-mspd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-egd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-esqd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-es24v.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-gd-df-dd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-generalUpdated.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-hre.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-hrs.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-jet-fans.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ksfv.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-lc-l2-l3.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-Losone-Select.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-lpd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-csf-lsf.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-md.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-mdx-es24vk.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pcxp.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pcd80xhp.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pcd110xiaqs.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pcd110xp.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pclp.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pclpd100xhp.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pclprd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pclpxp.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pcv.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-prf.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pv.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-pvdedpv.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-rcxii.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-refresh.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-rlx.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-sco2-w.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-sdb.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-sdbd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-SDBDe-STXDe-STXDeRHUL.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-sfm.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-smc-c.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-smxd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-smxd-ht.pdf',
'https://www.solerpalau-usa.com/documents/iom/iom-spbl-Updated.pdf',
'https://www.solerpalau-usa.com/documents/iom/iom-spbt.pdf',
'https://www.solerpalau-usa.com/documents/iom/iom-sptl.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-sqb.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-sqd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-STC7D.pdf',
'https://www.solerpalau-usa.com/documents/IOM/stxb-iom.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-stxd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-SDBDe-STXDe-STXDeRHUL.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-swf-sidewall.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tdb.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tdd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-td-mixvent(100-315).pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-td-mixvent(355-400).pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-td-silent.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tempest.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-jet-fans.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tornado.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tr(130-300).pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tr(90).pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-trc500.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-trc800.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-trc1200.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-trc1600.pdf',
'https://www.solerpalau-usa.com/documents/IOM/IOM-TRE.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tre90.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-TRLPe110.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tub.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-tub-ht.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ubb-ubx.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ubrd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ubs.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ubsrd.pdf',
'https://www.solerpalau-usa.com/documents/IOM/iom-ubsrd-ht.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-acf.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ar.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-bgh.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-cfd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-cm.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-csf.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ctb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-cwd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-dd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-df.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-egd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-esqd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-gd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-hre.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-hrs.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ifab-ifeb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ifft-iffte.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ksfv.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-l2.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-l3.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-lc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-E-series.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-EL-series.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-Losone-Select-Series.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-lpd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-lsf.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pc80x.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pc110xp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-PCD80XHP.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pdsub-pcd110xp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclp80.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclp80xp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclp100.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclp100xp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclpd100xhp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pcv.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-prf.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pv.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pvdedpv.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-rcxii(6-20).pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-rcxii(24-36).pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-rcxii-sf.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-refresh-full-size-units.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-refresh-low-profile.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-rfv8-120ac-es24v.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-rlx.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sdb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sdbd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-smxd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-smxd-ht.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sqb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sqd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-stxb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-stxb-ht-ht2.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-stxd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-swf.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tdb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tdd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-td-mixvent.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-td-silent.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tempest.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tjfu.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tornado.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tr130.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tr200.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tr300.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tr90.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tr90g.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-trc500.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-trc800.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-trc800v.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-trc1200.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-trc1600updated.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tre90.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tre200.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tre300.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-TRLPe110.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-TRLPe110H.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tub.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-tub-ht.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubrd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubs.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubsrd-ubsrd-p.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubsrd-ht.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubsrd-ht1.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ubx.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-304ss.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-411.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-611.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-2521.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-25255ul.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-2727-1.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-2828-1.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-6002.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-990076.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-990447.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-acd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-acl.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-acop.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-acop-v.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-boc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-bor.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-car.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-m8-m13-trc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-cs325.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-curb-cap-adaptor.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-cvc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-damper-birdscreen.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-def-d.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-dh6-120v.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ecowatt-drive.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-epbt60.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-es24v.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-filtered-wall-housing.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-fltd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ft247.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ft622.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-gmd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-gra.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sdb-roof-curb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ksfv-intake-extension.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-ksfv-fb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-lt-100.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-mar.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-mca.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-md.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-mdx-es24vk.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-me.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-mfl.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-mrj.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pc3s.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pcd110xmrd.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pchs.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pchsp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pciaqs.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pcledkp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclphs.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclphsp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclpsc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pclpscp.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pcsc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-per-cn.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-per-w.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pg.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-pie.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-r24v.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-rc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sc.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-scr.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-scs5.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-self-flashing-curb.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-Type-SFR-Special-Restaurant-Curbs.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-shw20.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sil.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-spt100x.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sr.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sr5-4.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-srt30.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-backdraft-damper.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-sy.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-eco-digital.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-eco-analog.pdf',
'https://www.solerpalau-usa.com/documents/Submittal/sub-vl.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/AR(E)(S).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/BGH.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/CFD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/CM.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/CSF.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/CTB(RHUL).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/CWD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/DD(E)(S).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/DF(E)(S).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/(e)SQD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/G(E)(S)D.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/HRE(B)(D)-C.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/HREB-P.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/HRS(B)(D).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/IFAB.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/IFEB.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/L2(E)(S).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/L3(E)(S).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/LC(E)(S).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/Losone-Select-Specs.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/LPD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/LSF.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/PVDEDPV.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/RCXII(SF).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/RLX.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/SDB.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/SDBD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/SDBDe.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/SMXD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/Spec-SMXD-HT.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/SQB.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/STXB(W).pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/SWF.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TD-MIXVENT.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TDB.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TDD.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TR-Residential.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TRC1200-TRCe1200.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TRC1600.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TUB.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/TUB-HT.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/UBB-UBX.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/UBS.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/UBSRD-UBSRD-P.pdf',
'https://www.solerpalau-usa.com/documents/Specsheet/UBSRD-HT.pdf'

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

].map(url => encodeURI(url));



// Install event: Cache resources when the service worker is installed
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(cacheName)
      .then((cache) => {
        const cachePromises = cacheResources.map(url => {
          return fetch(url).then(response => {
            if (response.ok) {
              return cache.put(url, response);
            } else {
              console.warn(`URL ${url} returned status ${response.status}`);
            }
          }).catch(error => {
            console.warn(`No response received for ${url}:`, error.message);
          });
        });
        return Promise.all(cachePromises);
      })
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Bypass service worker for Firebase SDKs or specific API requests
  if (url.origin === 'https://www.gstatic.com' && url.pathname.startsWith('/firebasejs')) {
      return fetch(event.request); // Perform a regular fetch
  }

  // Bypass service worker for Firebase Identity Toolkit API
  if (url.origin === 'https://identitytoolkit.googleapis.com' && url.pathname.startsWith('/v1/accounts:lookup')) {
      return fetch(event.request); // Perform a regular fetch
  }

  event.respondWith(
      caches.match(event.request)
          .then((response) => {
              // Return the cached response if found
              if (response) {
                  return response;
              }

              // For external resources, use no-cors mode
              const fetchOptions = event.request.mode === 'navigate' ? {} : { mode: 'no-cors' };

              // Fetch the resource from the network
              return fetch(event.request, fetchOptions).then((networkResponse) => {
                  // Don't cache opaque responses or responses that are not ok
                  if (!networkResponse.ok || networkResponse.type === 'opaque') {
                      return networkResponse;
                  }

                  // Clone and cache the response if it's ok
                  const responseToCache = networkResponse.clone();
                  caches.open(cacheName)
                      .then((cache) => {
                          cache.put(event.request, responseToCache);
                      });

                  return networkResponse;
              });
          })
  );
});




// Activate event: Clear old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.filter((oldCacheName) => {
          return oldCacheName !== cacheName; // Only delete caches that aren't the current cache
        }).map((oldCacheName) => {
          return caches.delete(oldCacheName); // Delete the old caches
        })
      );
    }).then(() => {
      // Take immediate control of the page
      return self.clients.claim();
    })
  );
});